<a href="https://colab.research.google.com/github/melbinmv/Learning/blob/main/Basic_Tensor_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
#Initialization of tensor

x = tf.constant(4) #Scalr tensor
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
x2 = tf.constant(4, shape=(1,1), dtype= float)
print(x2)


tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [8]:
x = tf.constant([[1,2,3],[4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [9]:
x = tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [11]:
x = tf.zeros((2,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [12]:
x = tf.eye(3) #Identity Matrix
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [13]:
x = tf.random.normal((3,3), mean =0, stddev=1)
print(x)

tf.Tensor(
[[ 1.8115704e-01 -9.5680279e-01  1.8279027e-03]
 [-2.0892491e+00  5.8116412e-01  1.3698012e+00]
 [-9.0282077e-01  8.9596462e-01  2.9950878e-02]], shape=(3, 3), dtype=float32)


In [14]:
x = tf.random.uniform((1,3), minval=0, maxval=1)
print(x)

tf.Tensor([[0.64703166 0.42685318 0.25308788]], shape=(1, 3), dtype=float32)


In [16]:
x = tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [17]:
x = tf.range(start =1, limit=10, delta=2)
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [19]:
#Change dtype
x = tf.cast(x, dtype = tf.float64)
print(x)

#tf.int(8,16.32,64), tf.bool

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


In [20]:
#Matematical Operations

In [21]:
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

z = tf.add(x,y) #z = x+y
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [23]:
z = tf.subtract(x,y)
print(z)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [24]:
z = tf.divide(x,y) #x/y
print(z)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [25]:
z = tf.multiply(x,y)
print(z)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [28]:
z = tf.tensordot(x,y, axes =1)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [29]:
z = tf.reduce_sum(x*y, axis =0)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [30]:
z = x ** 5
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [31]:
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))
z = tf.matmul(x,y)
print(z)
z = x @ y
print(z
      )

tf.Tensor(
[[-1.5673125  -3.0884738  -0.20611468 -0.03376202]
 [-0.8352062  -1.6652395  -1.7054384   1.3255843 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[-1.5673125  -3.0884738  -0.20611468 -0.03376202]
 [-0.8352062  -1.6652395  -1.7054384   1.3255843 ]], shape=(2, 4), dtype=float32)


In [32]:
#Indexing

In [35]:
x = tf.constant([0,1,1,2,3,1,2,2])
print(x[:])

tf.Tensor([0 1 1 2 3 1 2 2], shape=(8,), dtype=int32)


In [36]:
print(x[1:])

tf.Tensor([1 1 2 3 1 2 2], shape=(7,), dtype=int32)


In [37]:
print(x[1:3])

tf.Tensor([1 1], shape=(2,), dtype=int32)


In [38]:
print(x[::2])

tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)


In [39]:
print(x[::-1])

tf.Tensor([2 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [40]:
indices =tf.constant([0,3])
x_ind = tf.gather(x, indices)
print(x_ind)

tf.Tensor([0 2], shape=(2,), dtype=int32)


In [42]:
x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
print(x)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [43]:
print(x[:])

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [45]:
print(x[1:])

tf.Tensor(
[[3 4]
 [5 6]], shape=(2, 2), dtype=int32)


In [46]:
print(x[0:])

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [48]:
print(x[1,:])

tf.Tensor([3 4], shape=(2,), dtype=int32)


In [49]:
print(x[0:2])

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [50]:
#Reshaping

In [51]:
x = tf.range(9)

In [53]:
x = tf.reshape(x, (3,3))
print(x)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [54]:
print(tf.transpose(x,perm=[1,0]))

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
